### ISSUE TITLE
Software build with go

### ISSUE THREAD

**Issue by jaapdejong** [madisongh/meta-golang#10]
Hi All,
not really an issue...
Is there a common place to put recipes for packages build with go?
Thanks!
Jaap

**Comment by madisongh** [comment]
I've tried a couple of approaches in layers/distros I've put together, and they both worked OK:
* lump all recipes for go packages into one place (such as recipes-devtools/golang)
* distribute the recipes for go packages based on the functionality they provide (e.g., networking related under recipes-connectivity, support packages under recipes-support, etc.)

So there's no set pattern, just use an organization that makes sense to you, so you can easily locate the recipes when you need to work on them.
