### ISSUE TITLE
Trouble getting a demo app going

### ISSUE THREAD

**Issue by zwgraham** [madisongh/meta-golang#15]
Apologies for my ignorance here, but I'm working with a client that
wants us to include golang in our SDK generated by bitbake, but am a
newbie to go myself. **I would appreciate help figuring out my
configuration/golang-runtime problems**

We have an image-based SDK that I'm having trouble getting working
with go 1.8. I've added "nativesdk-golang" to our SDK packagegroup
recipe, then added the "go-runtime" to our image recipe.

To verify these steps include go1.8 in our SDK, I installed the SDK on
my workstation and checked the
/usr/local/sdkname/sysroots/x86_64-oesdk-linux/var/lib/opkg/ directory
for files related to nativesdk-golang and nativesdk-golang-runtime.

At this point I'm having trouble. When I source my sdk environment,
navigate to my go workspace (/home/username/go), and run some variant
of ```go build``` on a hello world program I get errors about the
runtime and standard libs not being found

my workspace
```
     user@host:~/go$ tree
     .
     ├── bin
     ├── pkg
     └── src
         └── subdir
             └── hello
                 └── hello.go
```

my go env
```
     user@host:~/go$ go env
     GOARCH="amd64"
     GOBIN=""
     GOEXE=""
     GOHOSTARCH="amd64"
     GOHOSTOS="linux"
     GOOS="linux"
     GOPATH="/home/user/go"
     GORACE=""
     GOROOT="/usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go"
     GOTOOLDIR="/usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go/pkg/tool/linux_amd64"
     GCCGO="gccgo"
     CC="arm-oe-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp
-mfpu=neon --sysroot=/usr/local/sdk-name/sysroots/armv7a-vfp-neon-oe-linux-gnueabi"
     GOGCCFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon
--sysroot=/usr/local/sdk-name/sysroots/armv7a-vfp-neon-oe-linux-gnueabi
-fPIC -m64 -pthread -fmessage-length=0
-fdebug-prefix-map=/tmp/go-build048326827=/tmp/go-build
-gno-record-gcc-switches"
     CXX="arm-oe-linux-gnueabi-g++ -march=armv7-a -mfloat-abi=softfp
-mfpu=neon --sysroot=/usr/local/sdk-name/sysroots/armv7a-vfp-neon-oe-linux-gnueabi"
     CGO_ENABLED="1"
     PKG_CONFIG="pkg-config"
     CGO_CFLAGS="-g -O2"
     CGO_CPPFLAGS=""
     CGO_CXXFLAGS="-g -O2"
     CGO_FFLAGS="-g -O2"
     CGO_LDFLAGS="-g -O2"
```

Contents of hello.go
```
package main

import "fmt"

func main() {
        fmt.Printf("Hello, world!\n")
}
```

Our goal is to produce output for ```GOARCH=arm GOARM=7 GOOS=linux``` so I change those when I try to build and get the following
```
user@host:~/go$ GOARCH=arm GOARM=7 go build subdir/hello
src/subdir/hello/hello.go:3:8: cannot find package "fmt" in any of:
        /usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go/src/fmt
(from $GOROOT)
        /home/user/go/src/fmt (from $GOPATH)
package subdir/hello
        imports math: cannot find package "math" in any of:
        /usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go/src/math
(from $GOROOT)
        /home/user/go/src/math (from $GOPATH)
package subdir/hello
        imports runtime: cannot find package "runtime" in any of:
        /usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go/src/runtime
(from $GOROOT)
        /home/user/go/src/runtime (from $GOPATH)
```
My $GOROOT directory tree

```
user@host:/usr/local/sdk-name/sysroots/x86_64-oesdk-linux/usr/lib/go$ tree
.
├── bin
│   ├── go
│   └── gofmt
└── pkg
    ├── linux_amd64_dynlink
    │   └── libstd.so
    └── tool
        └── linux_amd64
            ├── addr2line
            ├── api
            ├── asm
            ├── cgo
            ├── compile
            ├── cover
            ├── dist
            ├── doc
            ├── fix
            ├── link
            ├── nm
            ├── objdump
            ├── pack
            ├── pprof
            ├── trace
            └── vet
```

**Comment by madisongh** [comment]
Even though go automatically builds cross-compilation support into the toolchain, the recipes here are structured similar to gcc, and follow a similar naming pattern.

Assuming you're using the standard host, cross, and target packagegroups to populate your SDK, you would include `golang-cross-canadian-${TRANSLATED_TARGET_ARCH}` in the `packagegroup-cross-canadian` packagegroup.  You may also need to explicitly include both `golang-runtime` and `golang-runtime-dev` in `packagegroup-core-standalone-sdk-target`.  I've done that in my own SDKs, although I don't remember now whether it was really required or not.

**Comment by madisongh** [comment]
I've added a [page to the wiki](https://github.com/madisongh/meta-golang/wiki/SDK-support) with a note about this.
