### ISSUE TITLE
Binary not stripped 

### ISSUE THREAD

**Issue by jaapdejong** [madisongh/meta-golang#20]
For a piece of code I Found that the binary was not stripped. Doing it by hand created a much smaller file which still worked.
What should I do to automate this? 

Thanks!

**Comment by madisongh** [comment]
When I was first putting this together, stripping go-generated binaries caused them to break, so I disabled stripping during packaging.  That was several versions of Go back, though, and I should try enabling it again.

You can try it yourself by setting `INHIBIT_PACKAGE_STRIP = "0"` in your recipe, after the `inherit golang` line.

**Comment by jaapdejong** [comment]
That fixes the job!
Thanks for helping out!!
