### ISSUE TITLE
Long term plans

### ISSUE THREAD

**Issue by otavio** [madisongh/meta-golang#24]
Hello @madisongh 

First I'd like to congrats your work on this layer. It offers a much more complete support for Golang than OE-Core currently does. 

I am wondering what are your current long term plans regarding it as I think it would be good to send your improvements to OE-Core so you could share more work and also rely on Yocto Project CI and QA for it.

Are you intending to work on this?

**Comment by madisongh** [comment]
Thanks, @otavio.  I did offer to help with unifying the Go support in this layer with the other implementations when the initial OE-core work was done, but for whatever reasons, collaboration never happened, and by the time the OE-core recipes got to the review stage, what review comments I had were largely ignored.

Long-term, I do intend to retire this layer once the features here are in OE-core. The workload at my day job as been quite heavy over the last several months, so I haven't had the time to spend on making that happen.  I'm hoping I'll have more bandwidth for it soon.

**Comment by otavio** [comment]
This does concern me. Honestly, I am not sure it was a good move to add Go on OE-Core. Go itself is still changing rapidly and does require quite some love for better integration.

I think you did an outstanding work here. I am starting to take a look at the differences to try to port some parts of the work you did to the OE-Core but there are some fundamental changes which are not easy to adapt.

My focus now is to the Go class so we try to reduce the divergence as much as possible. Are you open to help on this?

**Comment by madisongh** [comment]
> Honestly, I am not sure it was a good move to add Go on OE-Core. Go itself is still changing rapidly and does require quite some love for better integration.

Agreed.

> I am starting to take a look at the differences to try to port some parts of the work you did to the OE-Core but there are some fundamental changes which are not easy to adapt.

Yes, there's a lot of work (and rework) to do there.

> Are you open to help on this?

I'll be happy to, and appreciate your pitching in on this, thanks!

**Comment by otavio** [comment]
I did send some initial patches to OE-Core. It brings some things you did and clean up some bits. 

There is still a lot to do and I would appreciate if you could take a look at our fork[1] and see what you'd do next.

1. https://github.com/OSSystems/oe-core/tree/wip/go

**Comment by madisongh** [comment]
This is great, thanks so much!

As for next steps, some further go.bbclass changes could be done - fixing the task function naming and using addtask, separating ${S} and ${B}, using go list to let the go tool identify the packages to build so you can implement GO_INSTALL_FILTEROUT, maybe the unpack function.

But the toolchain recipe changes might be better to tackle first:
1. move go runtime from ${STAGING_LIBDIR_NATIVE}/${TARGET_SYS} to the target sysroot
2. toolchain recipe cleanup and additions for nativesdk/crosssdk/cross-canadian

**Comment by otavio** [comment]
I will take a look but it seems to be it would be better to:

1. improve the go class (task naming, S and B and get filter out working)
2. work on recipe cleanup and additions

Are you going to work on any of those tasks?

**Comment by madisongh** [comment]
I've started a branch [here](https://github.com/madisongh/openembedded-core/commits/wip-go-updates), adding a patch for cleaning up task function naming on top of your series.

The S/B separation may not be doable without adding the unpack function, which may not be generally desirable.  I'll have to think about that one.  Adding the FILTEROUT support should probably go next.

I'll try and spend some time over the next few days working on some further updates.  If there is anything you'd like me to focus on specifically, let me know.

**Comment by otavio** [comment]
I think it is a good plan. I cherry-picked your patch and updated my branch with the current fixes. 

I think S/B separation should go in. Please add the unpack function and we see how it goes.

**Comment by madisongh** [comment]
I have pushed the patches for S/B separation and the unpack function to [my branch](https://github.com/madisongh/openembedded-core/commits/wip-go-updates).

**Comment by madisongh** [comment]
Everything is in OE-core now, so I think we can close this.  Thanks @otavio!
