### ISSUE TITLE
Support for Go 1.11

### ISSUE THREAD

**Issue by laibulle** [madisongh/meta-golang#27]
Hello, 

do you plane to release a Go 1.11 version ?

Best regards

**Comment by madisongh** [comment]
With Go support now present in OE-Core, I'm not doing much with meta-golang these days. An update to 1.11 recently went into OE-Core master.

**Comment by laibulle** [comment]
I didn't know that GO is in OE-Core. You should maybe set a [DEPRECATED] advice in the README.
