### ISSUE TITLE
Porting golang 1.9 to morty

### ISSUE THREAD

**Issue by dtoubelis** [madisongh/meta-golang#28]
Hi,
Would it be possible to port golang-1.9 recipe to morty? Are there any restrictions? Can I help in any sensible way?

We are stuck with yocto morty for alt least next few month but golang 1.8 is quite outdated and we more and more resorting to external builds with newer golang versions and it sucks. golang-1.9 would buy us some time.

Regards,
-Dmitri

**Comment by madisongh** [comment]
It should be relatively straightforward to back-port the 1.9 recipes from the pyro branch to morty, and then update the recipes to the latest 1.9.X maintenance release.  I'd be happy to take a PR for that.
