### ISSUE TITLE
cannot find section .rela.dyn on clean build

### ISSUE THREAD

**Issue by ernstp** [madisongh/meta-golang#8]
Hi,

I get the following errors on a clean build. However if you just build again this seems to be ignored and all is well.

ERROR: golang-cross-arm-1.6.3-r0 do_populate_sysroot_setscene: '('patchelf-uninative', '--set-interpreter', '/home/builder/workspace/project/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2', '/home/builder/workspace/project/tmp/work/x86_64-linux/golang-cross-arm/1.6.3-r0/sstate-install-populate_sysroot/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/bin/go')' failed with exit code 1 and the following output:
cannot find section .rela.dyn

WARNING: Logfile for failed setscene task is /home/builder/workspace/project/tmp/work/x86_64-linux/golang-cross-arm/1.6.3-r0/temp/log.do_populate_sysroot_setscene.7291
WARNING: Setscene task 673 (/home/builder/workspace/sources/meta-golang/recipes-devtools/golang/golang-cross_1.6.bb, do_populate_sysroot_setscene) failed with exit code '1' - real task will be run instead
ERROR: golang-native-1.6.3-r0 do_populate_sysroot_setscene: '('patchelf-uninative', '--set-interpreter', '/home/builder/workspace/project/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2', '/home/builder/workspace/project/tmp/work/x86_64-linux/golang-native/1.6.3-r0/sstate-install-populate_sysroot/x86_64-linux/usr/lib/go/bin/go')' failed with exit code 1 and the following output:
cannot find section .rela.dyn

WARNING: Logfile for failed setscene task is /home/builder/workspace/project/tmp/work/x86_64-linux/golang-native/1.6.3-r0/temp/log.do_populate_sysroot_setscene.12631
WARNING: Setscene task 1383 (/home/builder/workspace/sources/meta-golang/recipes-devtools/golang/golang-native_1.6.bb, do_populate_sysroot_setscene) failed with exit code '1' - real task will be run instead

**Comment by madisongh** [comment]
From what I can find, this is due to an incompatibility between patchelf and go-generated binaries.  This was fixed in oe-core morty with the update to patchelf 0.9 and the addition of a patch for [the issue](https://github.com/NixOS/patchelf/issues/66).

You can address this in krogoth by either disabling [uninative builds](http://www.yoctoproject.org/docs/2.1/mega-manual/mega-manual.html#ref-classes-uninative) or back-porting the patchelf update and re-generating your uninative tarball.

**Comment by ernstp** [comment]
Right, seems like a more generic problem. Backporting is a fine workaround,
cherry-picking d03439e0db02a0b6d165ca7da2d648add83d8649 in poky seems to do the trick.
